
[general]
	#When enabled, attacking a player-built golem will make it attack you
	friendly_fire = true
	#Percent chance for a villager to successfully summon an Extra Golems golem
	#Range: 0 ~ 100
	villager_summon_chance = 90
	#When true, only players in creative mode can use a Bedrock Golem spawn item
	bedrock_golem_creative_only = true
	#When enabled, players can 'use' the spell item on a carved pumpkin to convert it to a golem head in-world
	use_spell = true
	#(Experimental) When true, pumpkins can be used to build this mod's golems
	pumpkin_builds_golems = false
	#When enabled, some golems will change their texture when clicked
	texture_interact = false

[golem_coal]
	#Range: 1.0 ~ 999.0
	attack = 2.5
	#Range: 1.0 ~ 999.0
	health = 24.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_coal.specials]
		#Whether this golem can inflict blindness
		"Allow Special: Blindness" = false

[golem_straw]
	#Range: 1.0 ~ 999.0
	attack = 1.0
	#Range: 1.0 ~ 999.0
	health = 10.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_straw.specials]
		#Whether this golem can speed up crop growth
		"Allow Special: Crop Boost" = true
		#Minimum number of ticks between crop-boosts
		"Crop Boost Frequency" = 460

[golem_nether_brick]
	#Range: 1.0 ~ 999.0
	attack = 6.5
	#Range: 1.0 ~ 999.0
	health = 25.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_nether_brick.specials]
		#Whether this golem can light creatures on fire
		"Allow Special: Burn Enemies" = true

[golem_glass]
	#Range: 1.0 ~ 999.0
	attack = 13.0
	#Range: 1.0 ~ 999.0
	health = 8.0
	#Disables in-world building of the golem.
	enabled = true

[golem_concrete]
	#Range: 1.0 ~ 999.0
	attack = 5.0
	#Range: 1.0 ~ 999.0
	health = 38.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_concrete.specials]
		#Whether this golem reduces damage it takes
		"Allow Special: Resistance" = true

[golem_bookshelf]
	#Range: 1.0 ~ 999.0
	attack = 1.5
	#Range: 1.0 ~ 999.0
	health = 28.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_bookshelf.specials]
		#Whether this golem can give itself potion effects
		"Allow Special: Potion Effects" = true

[golem_emerald]
	#Range: 1.0 ~ 999.0
	attack = 18.0
	#Range: 1.0 ~ 999.0
	health = 190.0
	#Disables in-world building of the golem.
	enabled = true

[golem_gold]
	#Range: 1.0 ~ 999.0
	attack = 8.0
	#Range: 1.0 ~ 999.0
	health = 80.0
	#Disables in-world building of the golem.
	enabled = true

[golem_lapis]
	#Range: 1.0 ~ 999.0
	attack = 1.5
	#Range: 1.0 ~ 999.0
	health = 50.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_lapis.specials]
		#Whether this golem can inflict harmful potion effects
		"Allow Special: Potion Effects" = true

[golem_crafting]
	#Range: 1.0 ~ 999.0
	attack = 2.0
	#Range: 1.0 ~ 999.0
	health = 24.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_crafting.specials]
		#Whether this golem can open a crafting grid
		"Allow Special: Crafting" = true

[golem_leaves]
	#Range: 1.0 ~ 999.0
	attack = 1.0
	#Range: 1.0 ~ 999.0
	health = 6.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_leaves.specials]
		#Whether this golem can heal itself
		"Allow Special: Regeneration" = true

[golem_clay]
	#Range: 1.0 ~ 999.0
	attack = 2.0
	#Range: 1.0 ~ 999.0
	health = 20.0
	#Disables in-world building of the golem.
	enabled = true

[golem_nether_wart]
	#Range: 1.0 ~ 999.0
	attack = 1.5
	#Range: 1.0 ~ 999.0
	health = 22.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_nether_wart.specials]
		#Average number of ticks between planting nether wart (if enabled)
		"Netherwart Frequency" = 880
		#Whether this golem can plant netherwart randomly
		"Allow Special: Plant Netherwart" = true
		#Whether this golem can randomly heal (at night)
		"Allow Special: Random Healing" = true

[golem_prismarine]
	#Range: 1.0 ~ 999.0
	attack = 8.0
	#Range: 1.0 ~ 999.0
	health = 34.0
	#Disables in-world building of the golem.
	enabled = true

[golem_redstone_lamp]
	#Range: 1.0 ~ 999.0
	attack = 6.0
	#Range: 1.0 ~ 999.0
	health = 28.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_redstone_lamp.specials]
		#Whether this golem can light up the area
		"Allow Special: Emit Light" = true

[golem_stained_clay]
	#Range: 1.0 ~ 999.0
	attack = 4.0
	#Range: 1.0 ~ 999.0
	health = 42.0
	#Disables in-world building of the golem.
	enabled = true

[golem_sponge]
	#Range: 1.0 ~ 999.0
	attack = 1.5
	#Range: 1.0 ~ 999.0
	health = 20.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_sponge.specials]
		#Number of ticks between each water-check; increase to reduce lag
		"Water Soaking Frequency" = 10
		#Whether this golem can absorb water
		"Allow Special: Absorb Water" = true
		#Radial distance at which this golem can absorb water (Warning: larger values cause lag)
		"Water Soaking Range" = 5

[golem_hardened_clay]
	#Range: 1.0 ~ 999.0
	attack = 4.0
	#Range: 1.0 ~ 999.0
	health = 42.0
	#Disables in-world building of the golem.
	enabled = true

[golem_stained_glass]
	#Range: 1.0 ~ 999.0
	attack = 12.0
	#Range: 1.0 ~ 999.0
	health = 9.0
	#Disables in-world building of the golem.
	enabled = true

[golem_redstone]
	#Range: 1.0 ~ 999.0
	attack = 2.0
	#Range: 1.0 ~ 999.0
	health = 18.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_redstone.specials]
		#Whether this golem can emit redstone power
		"Allow Special: Redstone Power" = true

[golem_wooden]
	#Range: 1.0 ~ 999.0
	attack = 3.0
	#Range: 1.0 ~ 999.0
	health = 20.0
	#Disables in-world building of the golem.
	enabled = true

[golem_diamond]
	#Range: 1.0 ~ 999.0
	attack = 20.0
	#Range: 1.0 ~ 999.0
	health = 220.0
	#Disables in-world building of the golem.
	enabled = true

[golem_red_sandstone]
	#Range: 1.0 ~ 999.0
	attack = 4.0
	#Range: 1.0 ~ 999.0
	health = 22.0
	#Disables in-world building of the golem.
	enabled = true

[golem_slime]
	#Range: 1.0 ~ 999.0
	attack = 2.5
	#Range: 1.0 ~ 999.0
	health = 58.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_slime.specials]
		#When true, this golem will split into 2 mini-golems upon death
		"Allow Special: Split" = true
		#Slime Golem knockback power (Higher Value = Further Knockback)
		"Knockback Factor" = 1.0412
		#Whether this golem can apply extra knockback when attacking
		"Allow Special: Extra Knockback" = true

[golem_melon]
	#Range: 1.0 ~ 999.0
	attack = 1.5
	#Range: 1.0 ~ 999.0
	health = 18.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_melon.specials]
		#Average number of ticks between planting flowers
		"Flower Frequency" = 240
		#Whether this golem can plant flowers randomly
		"Allow Special: Plant Flowers" = true
		#Whether this golem can occasionally heal
		"Allow Special: Random Healing" = true

[golem_quartz]
	#Range: 1.0 ~ 999.0
	attack = 8.5
	#Range: 1.0 ~ 999.0
	health = 85.0
	#Disables in-world building of the golem.
	enabled = true

[golem_bedrock]
	#Range: 1.0 ~ 999.0
	attack = 32.0
	#Range: 1.0 ~ 999.0
	health = 999.0
	#Disables in-world building of the golem.
	enabled = true

[golem_glowstone]
	#Range: 1.0 ~ 999.0
	attack = 12.0
	#Range: 1.0 ~ 999.0
	health = 8.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_glowstone.specials]
		#Whether this golem can glow
		"Allow Special: Emit Light" = true

[golem_sandstone]
	#Range: 1.0 ~ 999.0
	attack = 4.0
	#Range: 1.0 ~ 999.0
	health = 22.0
	#Disables in-world building of the golem.
	enabled = true

[golem_wool]
	#Range: 1.0 ~ 999.0
	attack = 1.0
	#Range: 1.0 ~ 999.0
	health = 10.0
	#Disables in-world building of the golem.
	enabled = true

[golem_ice]
	#Range: 1.0 ~ 999.0
	attack = 6.0
	#Range: 1.0 ~ 999.0
	health = 18.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_ice.specials]
		#When true, this golem places frosted (temporary) ice
		"Use Frosted Ice" = false
		#Radial distance at which this golem can freeze / cool liquids (0=disable)
		"Area of Effect" = 3

[golem_obsidian]
	#Range: 1.0 ~ 999.0
	attack = 18.0
	#Range: 1.0 ~ 999.0
	health = 120.0
	#Disables in-world building of the golem.
	enabled = true

[golem_end_stone]
	#Range: 1.0 ~ 999.0
	attack = 8.0
	#Range: 1.0 ~ 999.0
	health = 50.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_end_stone.specials]
		#Whether the Endstone Golem takes damage from water
		"Can Take Water Damage" = true
		#Whether this golem can teleport
		"Allow Special: Teleporting" = true

[golem_bone]
	#Range: 1.0 ~ 999.0
	attack = 9.5
	#Range: 1.0 ~ 999.0
	health = 40.0
	#Disables in-world building of the golem.
	enabled = true

[golem_shroom]
	#Range: 1.0 ~ 999.0
	attack = 3.0
	#Range: 1.0 ~ 999.0
	health = 30.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_shroom.specials]
		#Whether this golem can plant mushrooms randomly
		"Allow Special: Plant Mushrooms" = true
		#Whether this golem can randomly heal (at night)
		"Allow Special: Random Healing" = true
		#Average number of ticks between planting mushrooms
		"Mushroom Frequency" = 420

[golem_sea_lantern]
	#Range: 1.0 ~ 999.0
	attack = 6.0
	#Range: 1.0 ~ 999.0
	health = 34.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_sea_lantern.specials]
		#Whether this golem lights up the area
		"Allow Special: Emit Light" = true

[golem_magma]
	#Range: 1.0 ~ 999.0
	attack = 4.5
	#Range: 1.0 ~ 999.0
	health = 46.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_magma.specials]
		#When true, this golem will split into 2 mini-golems upon death
		"Allow Special: Split" = true
		#When true, water will hurt this golem
		"Enable Water Damage" = true
		#Whether this golem can light creatures on fire
		"Allow Special: Burn Enemies" = true
		#Whether this golem can slowly melt cobblestone
		"Allow Special: Melt Cobblestone" = false
		#Number of ticks it takes to melt cobblestone if enabled (12 sec * 20 t/sec = 240 t)
		"Melting Delay" = 240

[golem_coral]
	#Range: 1.0 ~ 999.0
	attack = 6.0
	#Range: 1.0 ~ 999.0
	health = 38.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_coral.specials]
		#Number of ticks golem can stay out of water before drying out
		"Max Wet Time" = 425
		#Whether this golem can occasionally heal when wet
		"Allow Special: Healing" = true

[golem_tnt]
	#Range: 1.0 ~ 999.0
	attack = 2.5
	#Range: 1.0 ~ 999.0
	health = 14.0
	#Disables in-world building of the golem.
	enabled = true

	[golem_tnt.specials]
		#Whether this golem can explode when fighting or dying
		"Allow Special: Explode" = true

