
#Tweaks
[Tweaks]
	#Want a way to clear text in signs?
	enableSignEditing = true
	#Want to be able to sit on slabs and stairs?
	enableSit = true
	#Stack size for boat
	#Range: 1 ~ 64
	boatStackSize = 4
	#Want to shear nametag of named entities?
	shearOffNameTag = true
	#Want to shift click item frame to rotate in the reverse direction?
	itemFrameRotateBackwards = true
	#Want to disable shift in GUI due to potions?
	disablePotionShift = true
	#Want hoe to act like a sickle?
	hoeActsAsSickle = true
	#Want baby zombies to burn by the light of the day?
	babyZombieBurnInDaylight = true
	#Want sponge's placed in nether to dry?
	drySpongesInNether = true
	#Want command block to appear in redstone tab?
	commandBlockInRedstone = true
	#Want an way to swap armor with armor stand?
	enableArmorStandSwapping = true
	#Want the fire arrows to set fire on block it landed?
	arrowsSetBlockOnFire = true
	#Do you want to neglect fall damage and get water spilled when you fall on a wet sponge?
	squishySponge = true
	#Want creeper's to burn in daylight?
	creeperBurnInDaylight = true
	#Want TNT to ignite when next to lava or magma block?
	tntIgnition = true
	#Stack size for ender pearls
	#Range: 1 ~ 64
	enderPearlStackSize = 64
	#Want the ability to move spawners with silk touch?
	enableSilkSpawner = true
	#Want dragon egg to appear in decorations tab?
	dragonEggInDecorations = true

