
["Dog Constants"]
	#Determines if dogs die when their health reaches zero. If true, dogs will not die, and will instead become incapacitated.
	enable_immortality = true
	#The time in ticks it takes for a baby dog to become an adult, default 48000 (2 Minecraft days) and minimum 0
	#Range: > 0
	time_to_mature = 48000
	#Disable hunger mode for the dog
	disable_hunger = false
	#When enabled you will spawn with a guide, Doggy Charm and Command Emblem.
	enable_starting_items = false
	#When enabled, dogs will be randomly assigned genders and will only mate and produce children with the opposite gender.
	enable_gender = true
	#Determines if dogs should whine when hunger reaches below 20 DP.
	whine_when_hungry = true
	#When enabled, puppies get some levels from parents. When disabled, puppies start at 0 points.
	enable_pup_get_parent_levels = false
	#The item resource path that can be used to revive an incapacitated dog. If item is not valid defaults to minecraft:cake
	revive_item = "minecraft:cake"

