
[spawn]
	# This determines the spawn rate of berry bushes (1/n). Set this to 0 will disable the spawn.
	#Range: 0 ~ 50
	spawn_rate = 25

	[spawn.banned]
		# Bushes spawn will exclude the dimensions that id is in this list
		banned_dim = [-1, 1]
		# Bushes spawn will exclude the biomes that id is in this list
		banned_biome = ["minecraft:ocean", "minecraft:desert", "minecraft:nether", "minecraft:the_end", "minecraft:frozen_ocean", "minecraft:frozen_river", "minecraft:desert_hills", "minecraft:deep_ocean", "minecraft:stone_shore", "minecraft:badlands", "minecraft:small_end_islands", "minecraft:end_midlands", "minecraft:end_highlands", "minecraft:end_barrens", "minecraft:warm_ocean", "minecraft:lukewarm_ocean", "minecraft:cold_ocean", "minecraft:deep_warm_ocean", "minecraft:deep_lukewarm_ocean", "minecraft:deep_cold_ocean", "minecraft:deep_frozen_ocean", "minecraft:the_void"]

	[spawn.height]
		# This defines the min y that a bush is able to spawn at
		#Range: 0 ~ 256
		spawn_min = 54
		# This defines the max y that a bush is able to spawn at
		#Range: 0 ~ 256
		spawn_max = 80

[prop]
	# There is a 1/n of chance that a bush will grow on a random tick
	#Range: 1 ~ 12
	growth_rate = 6
	# Does the bushes hurt livings like cactus
	bush_hurt = true
	# Berry Bushes will drop their berry if this is set to true
	mature_drop = true

