"CharmEnchanting module enabled" = true
"CharmBrewing module enabled" = true
"CharmDecoration module enabled" = true
"CharmCrafting module enabled" = true
"CharmWorld module enabled" = true
"CharmTweaks module enabled" = true
"CharmAutomation module enabled" = true

[CharmDecoration]
	#GoldLantern
	"GoldLantern feature enabled" = true
	#RandomAnimalTextures
	"RandomAnimalTextures feature enabled" = true
	#AllTheBarrels
	"AllTheBarrels feature enabled" = true

[CharmTweaks]
	#ExtraRecords
	"ExtraRecords feature enabled" = true
	#RecordsStopBackgroundMusic
	"RecordsStopBackgroundMusic feature enabled" = true
	#As long as a Totem of Undying is in your inventory, it will be consumed to protect you from death.
	"UseTotemFromInventory feature enabled" = true
	#AutomaticRecipeUnlock
	"AutomaticRecipeUnlock feature enabled" = true
	#StackablePotions
	"StackablePotions feature enabled" = true
	#StackableEnchantedBooks
	"StackableEnchantedBooks feature enabled" = true
	#TamedAnimalsNoDamage
	"TamedAnimalsNoDamage feature enabled" = true
	#RemovePotionGlint
	"RemovePotionGlint feature enabled" = true
	#PickaxesBreakPistons
	"PickaxesBreakPistons feature enabled" = true

[CharmEnchanting]
	#Magnetic
	"Magnetic feature enabled" = true

	[CharmEnchanting.Magnetic]
		#Drops within this range of the player will be picked up.
		"Attraction range" = 6

[CharmWorld]
	#Gold deposits spawn in the Nether that can be broken to receive gold nuggets.
	"NetherGoldDeposits feature enabled" = true
	#StructureMaps
	"StructureMaps feature enabled" = true
	#CompassBinding
	"CompassBinding feature enabled" = true

	[CharmWorld.CompassBinding]
		#If true, compasses can bind to banners.
		"Bind to Banners" = false
		#If true, compasses can bind to beacons.
		"Bind to Beacons" = true

	[CharmWorld.StructureMaps]
		#Minimum emerald cost of a general structure map.
		"General map minimum cost" = 4
		#Maximum emerald cost of a biome-specific structure map.
		"Biome-specific map maximum cost" = 22
		#Minimum emerald cost of a biome-specific structure map.
		"Biome-specific map minimum cost" = 16
		#Maximum number the trade can be used before it locks.
		"Maximum trades" = 1
		#The amount of experience awarded to the villager upon selling.
		"Villager experience awarded" = 5
		#Maximum emerald cost of a general structure map.
		"General map maximum cost" = 7
		#The level at which a cartographer will trade structure maps.
		#Numbers correspond to villager level, starting at 1 for Novice.
		"Trade level" = 3

[CharmAutomation]
	#RedstoneSand
	"RedstoneSand feature enabled" = true
	#VariableRedstoneLamp
	"VariableRedstoneLamp feature enabled" = true
	#GunpowderBlock
	"GunpowderBlock feature enabled" = true

[CharmBrewing]
	#Decay
	"Decay feature enabled" = true
	#Coffee
	"Coffee feature enabled" = true
	#FlavoredCake
	"FlavoredCake feature enabled" = true

	[CharmBrewing.FlavoredCake]
		#Duration multiplier of the potion effect when eating a single slice of cake.
		"Effect duration multiplier" = 0.1

[CharmCrafting]
	#EnderPearlBlock
	"EnderPearlBlock feature enabled" = true
	#Crate
	"Crate feature enabled" = true

	[CharmCrafting.EnderPearlBlock]
		#If true, eating a Chorus Fruit while in range of an Ender Pearl Block will teleport you to it.
		"Teleport stabilization" = true

