
#Enable or disable certain items. Disabled items will not be craftable and will not generate in dungeons
["Accesibility Config"]
	#Whether or not Blazing Core should be enabled.
	blazingCoreEnabled = true
	#Whether or not Unholy Grail should be enabled.
	unholyGrailEnabled = true
	#Whether or not Ultimate Potions should be enabled.
	ultimatePotionsEnabled = true
	#Whether or not Scroll of Postmortal Recall should be enabled.
	escapeScrollEnabled = true
	#Whether or not Etherium Tools should be enabled.
	etheriumToolsEnabled = true
	#Whether or not Axe of Executioner should be enabled.
	forbiddenAxeEnabled = true
	#Whether or not Charm of Treasure Hunter should be enabled.
	miningCharmEnabled = true
	#Whether or not Mending Mixture should be enabled.
	mendingMixtureEnabled = true
	#Whether or not Emblem of Monster Slayer should be enabled.
	monsterCharmEnabled = true
	#Whether or not Pearl of the Void should be enabled.
	voidPearlEnabled = true
	#Whether or not Arcane Inscriber should be enabled.
	loreInscriberEnabled = true
	#Whether or not Gift of the Heaven should be enabled.
	heavenScrollEnabled = true
	#Whether or not Iron Ring should be enabled.
	ironRingEnabled = true
	#Whether or not Potion of Haste should be enabled.
	hastePotionEnabled = true
	#Whether or not Magnetic Ring should be enabled.
	magnetRingEnabled = true
	#Whether or not Ender Ring should be enabled.
	enderRingEnabled = true
	#Whether or not new conventional potions should be enabled. This includes only Haste potions, currently.
	commonPotionsEnabled = true
	#Whether or not Heart of the Golem should be enabled.
	golemHeartEnabled = true
	#Whether or not Potion of Recall should be enabled.
	recallPotionEnabled = true
	#Whether or not Extradimensional Eye should be enabled.
	extradimensionalEyeEnabled = true
	#Whether or not Eye of the Nebula should be enabled.
	eyeOfNebulaEnabled = true
	#Whether or not Ring of Dislocation should be enabled.
	superMagnetRingEnabled = true
	#Whether or not Extrapolated Megasponge should be enabled.
	megaSpongeEnabled = true
	#Whether or not Will of the Ocean should be enabled.
	oceanStoneEnabled = true
	#Whether or not Angel's Blessing should be enabled.
	angelBlessingEnabled = true
	#Whether or not Scroll of Ageless Wisdom should be enabled.
	xpScrollEnabled = true
	#Whether or not Etherium Armor should be enabled.
	etheriumArmorEnabled = true

#Just some different stuff
["Generic Config"]
	#Version of config file. DO NOT MODIFY UNLESS YOU KNOW EXACTLY WHAT YOU'RE DOING!
	configVersion = "1.0"
	#Whether or not Dislocation Ring should play any sounds when teleporting items to it's bearer.
	superMagnetRingSound = true

#Various options that affect individual items
["Balance Options"]
	#Damage multiplier against undead enemies for Emblem of Monster Slayer. Defined as percentage.
	#Range: 0 ~ 1000
	monsterCharmUndeadDamage = 25
	#Mining speed boost granted by Charm of Treasure Hunter. Defined as percentage.
	#Range: 0 ~ 1000
	miningCharmBreakBoost = 50
	#Damage reduction of shield generated by Etherium Armor. Defined as percentage.
	#Range: 0 ~ 100
	etheriumArmorShieldReduction = 50
	#Additional block reach granted by Charm of Treasure Hunter.
	#Range: 0.0 ~ 16.0
	miningCharmBlockReach = 2.15
	#Whether or not Charm of Treasure Hunter should provide +1 Luck.
	miningCharmBonusLuck = true
	#The value of health to which player wearing full Etherium Armor set should be brough to activate the shield ability. Defined as percentage.
	#Range: 0 ~ 100
	etheriumArmorShieldThreshold = 40
	#Default chance to behead an enemy with Axe of Executioner. Defined as percentage.
	#Range: 0 ~ 100
	forbiddenAxeBeheadingBase = 10
	#Bonus percantage to beheading chance from each looting level applied to Axe of Executioner.
	#Range: 0 ~ 100
	forbiddenBeheadingBonus = 5
	#Whether or not Emblem of Monster Slayer should provide double experience drop from monsters.
	monsterCharmBonusXP = true
	#The radius in which Magnetic Ring will attract items.
	#Range: 1 ~ 32
	magnetRingRange = 8
	#The volume Etherium Scythe AOE harvesting. Set to -1 to disable the feature.
	#Range: -1 ~ 99
	etheriumScytheVolume = 3
	#The radius of Etherium Shovel AOE digging. Set to -1 to disable the feature.
	#Range: -1 ~ 99
	etheriumShovelRadius = 3
	#The depth of Etherium Shovel AOE digging.
	#Range: 1 ~ 99
	etheriumShovelDepth = 1
	#Range in which Scroll of Ageless Wisdom collects experience orbs when active.
	#Range: 1.0 ~ 128.0
	xpScrollCollectionRange = 16.0
	#Radius in which Exptrapolated Megaspong absorbs water. Default 4 equals to vanilla sponge
	#Range: 0 ~ 128
	megaspongeRadius = 4
	#Whether or not Emblem of Monster Slayer should provide +1 Looting Level.
	monsterCharmBonusLooting = true
	#The radius in which Dislocation Ring will collect items.
	#Range: 1 ~ 128
	superMagnetRingRange = 16
	#Cooldown of Etherium Broadsword ability. Measured in ticks.
	#Range: 0 ~ 32768
	etheriumSwordCooldown = 40
	#Damage multiplier against agressive creatures for Emblem of Monster Slayer. Defined as percentage.
	#Range: 0 ~ 1000
	monsterCharmAgressiveDamage = 10
	#The depth of Etherium Pickaxe AOE mining.
	#Range: 1 ~ 99
	etheriumPickaxeDepth = 1
	#Multiplier for experience consumption by Gift of the Heaven.
	#Range: 0.0 ~ 1000.0
	heavenScrollXPCostModifier = 1.0
	#The radius of Etherium Pickaxe AOE mining. Set to -1 to disable the feature.
	#Range: -1 ~ 99
	etheriumPickaxeRadius = 3
	#The volume Etherium Waraxe AOE chopping. Set to -1 to disable the feature.
	#Range: -1 ~ 99
	etheriumAxeVolume = 3

#Balancing and other option for all the spellstones
["Spellstones Options"]
	#How much fire-based damage instantly receives any creature that attacks bearer of the Blazing Core.
	#Range: 0.0 ~ 512.0
	blazingCoreDamageFeedback = 4.0
	#Active ability cooldown for Heart of Creation. Measured in ticks. 20 ticks equal to 1 second.
	#Range: 0 ~ 32768
	enigmaticItemCooldown = 3
	#The amount of armor toughness provided by Heart of the Golem when it's bearer has no armor equipped.
	#Range: 0.0 ~ 256.0
	golemHeartSuperArmorToughness = 4.0
	#Modifier for Magic Damage vulnerability applied by Heart of the Golem. Default value of 2.0 means that player will receive twice as much damage from magic.
	#Range: 1.0 ~ 256.0
	golemHeartVulnerabilityModifier = 2.0
	#How how many seconds any creature that attacks bearer of the Blazing Core will be set on fire.
	#Range: 0 ~ 512
	blazingCoreIgnitionFeedback = 4
	#Base damage dealt by Darkness every half a second, when it devours a creature in proximity of bearer of the pearl.
	#Range: 0.0 ~ 1000.0
	voidPearlBaseDarknessDamage = 4.0
	#Chance for Pearl of the Void to prevent it's bearer death from receiving lethal amout of damage. Defined as percentage.
	#Range: 0 ~ 100
	voidPearlUndeadChance = 15
	#Acceleration modifier for active ability of Angel's Blessing. The greater it is, the more momentum you will gain.
	#Range: 0.0 ~ 256.0
	angelBlessingAccelerationModifier = 1.0
	#Range in which Pearl of the Void will force darkness to devour living creatures.
	#Range: 0.0 ~ 128.0
	voidPearlShadowRange = 16.0
	#Active ability cooldown for Blazing Core. Measured in ticks. 20 ticks equal to 1 second.
	#Range: 0 ~ 32768
	blazingCoreCooldown = 0
	#Range in which Eye of the Nebula can reach an entity when using it's active ability.
	#Range: 1.0 ~ 128.0
	eyeOfNebulaPhaseRange = 32.0
	#The amount of armor points provided by Heart of the Golem when it's bearer has no armor equipped.
	#Range: 0.0 ~ 256.0
	golemHeartSuperArmor = 16.0
	#Resistance to explosion damage provided by Heart of the Golem. Defined as percentage.
	#Range: 0 ~ 100
	golemHeartExplosionResistance = 40
	#Resistance to melee attacks provided by Heart of the Golem. Defined as percentage.
	#Range: 0 ~ 100
	golemHeartMeleeResistance = 25
	#Active ability cooldown for Pearl of the Void. Measured in ticks. 20 ticks equal to 1 second.
	#Range: 0 ~ 32768
	voidPearlCooldown = 0
	#Modifier for slowing down player's regeneration when bearing the pearl. This includes natural regeneration, as well as artificial healing effects that work over time. The greater it is, the slower player will regenerate.
	#Range: 0.0 ~ 1000.0
	voidPearlRegenerationModifier = 1.0
	#Amout of ticks for which bearer of the pearl will apply Withering effect to entities they attack. 20 ticks equals to 1 second.
	#Range: 0 ~ 32768
	voidPearlWitheringTime = 100
	#Damage resistance against underwater creatures provided by Will of the Ocean. Defined as percentage.
	#Range: 0 ~ 100
	oceanStoneUnderwaterCreaturesResistance = 50
	#Default amount of armor points provided by Heart of the Golem.
	#Range: 0.0 ~ 256.0
	golemHeartDefaultArmor = 4.0
	#Separate acceleration modifier for active ability of Angel's Blessing when player is flying with Elytra.
	#Range: 0.0 ~ 256.0
	angelBlessingAccelerationModifierElytra = 0.6
	#Range in which Eye of the Nebula searches for a position to teleport it's bearer to when dodging the attack.
	#Range: 1.0 ~ 128.0
	eyeOfNebulaDodgeRange = 16.0
	#Active ability cooldown for Eye of the Nebula. Measured in ticks. 20 ticks equal to 1 second.
	#Range: 0 ~ 32768
	eyeOfNebulaCooldown = 60
	#Magic Damage resistance provided by Eye of the Nebula. Defined as percentage.
	#Range: 0 ~ 100
	eyeOfNebulaMagicResistance = 65
	#Level of Withering that bearer of the pearl will apply to entitities they attack.
	#Range: 0 ~ 3
	voidPearlWitheringLevel = 2
	#Active ability cooldown for Heart of the Golem. Measured in ticks. 20 ticks equal to 1 second.
	#Range: 0 ~ 32768
	golemHeartCooldown = 0
	#Resistance to knockback provided by Heart of the Golem. Defined as percentage.
	#Range: 0 ~ 100
	golemHeartKnockbackResistance = 100
	#Swimming speed boost provided by Will of the Ocean. Defined as percentage.
	#Range: 0 ~ 1000
	oceanStoneSwimBoost = 200
	#Probability for Eye of the Nebula to teleport it's bearer from any attack without receiving any damage. Defined as percentage.
	#Range: 0 ~ 100
	eyeOfNebulaDodgeChance = 15
	#Active ability cooldown for Angel's Blessing. Measured in ticks. 20 ticks equal to 1 second.
	#Range: 0 ~ 32768
	angelBlessingCooldown = 40
	#Active ability cooldown for Will of the Ocean. Measured in ticks. 20 ticks equal to 1 second.
	#Range: 0 ~ 32768
	oceanStoneCooldown = 600
	#Multiplier for experience consumption by active ability of Will of the Ocean.
	#Range: 0.0 ~ 1000.0
	oceanStoneXPCostModifier = 1.0

