
[General]
	#The radius around the campfire in blocks where players receive the regeneration effect.
	#Range: 1 ~ 64
	healingRadius = 16
	#The duration of the regeneration effect which the campfire applies.
	#Range: 1 ~ 600
	effectDurationSeconds = 60
	#When enabled, the campfire heals passive mobs around where the radius is half the width of a bounding box.
	healPassiveMobs = true

