
#Disable and configure tweaks.
[Tweaks]
	#Enabled tools not breaking?
	toolBreaking = true

#Crafting grid tool repair configuration options.
["Grid Repair"]
	#Makes it so shovels need 50% less material to repair.
	cheapShovel = true
	#How much material should be required to fully repair a tool.
	#Range: 1 ~ 8
	cost = 4
	#Should default repair materials be disabled? Doing this makes it so ONLY the custom materials work.
	disableDefaults = false
	#Should Crafting Grid Tool Repairing be enabled?
	enabled = true
	#Enabling this makes it so custom repair materials override the default ones for the tools specified.
	overrideMode = false

#General configuration options.
[General]
	#The effective radius of the Magnet.
	#Range: 1.0 ~ 16.0
	magnetRange = 7.0

#Disable features.
[Features]
	#Enable Flint tools and armor?
	flintGear = true
	#Dark Glass enabled?
	darkGlass = true
	#Enable Emerald tools and armor?
	emeraldGear = true
	#Enable right click crop harvesting?
	rightClickHarvest = true
	#Colored Cobblestone enabled?
	coloredCobblestone = true
	#Watering Can enabled?
	wateringCan = true
	#Enable Paxels?
	paxels = true
	#Enable Night Vision Goggles?
	nightVisionGoggles = true
	#Diamond and Emerald Apples enabled?
	apples = true
	#Enable Magnet?
	magnet = true
	#Coal and Charcoal Piece enabled?
	coalPiece = true
	#Enable Meshes?
	meshes = true

