
#Beginning of QuarryPlus configuration.
[common]
	#True to allow machines to remove bedrock. (Just removing. Not collecting)
	RemoveBedrock = false
	#True to enable ChunkDestroyer to collect bedrock as item.
	CollectBedrock = false
	#True to make machines work with no energy.
	NoEnergy = false
	#True to enable debug mode.
	debug = false
	#Fasten quarry's head moving.
	FastQuarryHeadMove = false
	#Spawner Controller Blacklist
	spawnerBlacklist = ["minecraft:ender_dragon", "minecraft:wither", "minecraft:area_effect_cloud", "minecraft:item", "minecraft:player"]
	#Amount of energy WorkbenchPlus can receive in a tick. [MJ]
	#Range: > 0
	WorkbenchMaxReceive = 250
	#Set false to allow PlumPlus to remove non-source fluid block.
	RemoveOnlyFluidSource = false
	#DisableFrameChainBreak
	DisableFrameChainBreak = false

	#Quarry PowerSetting [MJ] (min = 0, Max = 2,000,000,000 = 2 billion)
	[common.PowerSetting]

		[common.PowerSetting.Laser]
			#Range: 0.0 ~ 2.0E9
			UnbreakingCoefficient = 0.1
			#Range: 0.0 ~ 2.0E9
			EfficiencyCoefficient = 2.0
			#Range: 0.0 ~ 2.0E9
			FortuneCoefficient = 1.05
			#Range: 0.0 ~ 2.0E9
			SilktouchCoefficient = 1.1
			#Range: 0.0 ~ 2.0E9
			BaseMaxReceive = 100.0
			#Range: 0.0 ~ 2.0E9
			BasePower = 4.0
			#Range: 0.0 ~ 2.0E9
			BaseMaxStored = 1000.0

		[common.PowerSetting.Quarry]

			[common.PowerSetting.Quarry.MakeFrame]
				#Range: 0.0 ~ 2.0E9
				UnbreakingCoefficient = 1.0
				#Range: 0.0 ~ 2.0E9
				EfficiencyCoefficient = 1.3
				#Range: 0.0 ~ 2.0E9
				BaseMaxReceive = 100.0
				#Range: 0.0 ~ 2.0E9
				BasePower = 25.0
				#Range: 0.0 ~ 2.0E9
				BaseMaxStored = 15000.0

			[common.PowerSetting.Quarry.BreakBlock]
				#Range: 0.0 ~ 2.0E9
				UnbreakingCoefficient = 1.0
				#Range: 0.0 ~ 2.0E9
				EfficiencyCoefficient = 1.3
				#Range: 0.0 ~ 2.0E9
				FortuneCoefficient = 1.3
				#Range: 0.0 ~ 2.0E9
				SilktouchCoefficient = 2.0
				#Range: 0.0 ~ 2.0E9
				BaseMaxReceive = 300.0
				#Range: 0.0 ~ 2.0E9
				BasePower = 40.0
				#Range: 0.0 ~ 2.0E9
				BaseMaxStored = 15000.0

				[common.PowerSetting.Quarry.BreakBlock.MoveHead]
					#Range: 0.0 ~ 2.0E9
					UnbreakingCoefficient = 1.0
					#Range: 0.0 ~ 2.0E9
					BasePower = 200.0

		[common.PowerSetting.Refinery]
			#Range: 0.0 ~ 2.0E9
			UnbreakingCoefficient = 1.0
			#Range: 0.0 ~ 2.0E9
			EfficiencyCoefficient = 1.2
			#Range: 0.0 ~ 2.0E9
			BaseMaxReceive = 6.0
			#Range: 0.0 ~ 2.0E9
			BaseMaxStored = 1000.0

		[common.PowerSetting.Pump]

			[common.PowerSetting.Pump.DrainLiquid]
				#Range: 0.0 ~ 2.0E9
				UnbreakingCoefficient = 1.0
				#Range: 0.0 ~ 2.0E9
				BasePower = 10.0

			[common.PowerSetting.Pump.MakeFrame]
				#Range: 0.0 ~ 2.0E9
				UnbreakingCoefficient = 1.0
				#Range: 0.0 ~ 2.0E9
				BasePower = 25.0

		[common.PowerSetting.MiningWell]
			#Range: 0.0 ~ 2.0E9
			UnbreakingCoefficient = 1.0
			#Range: 0.0 ~ 2.0E9
			EfficiencyCoefficient = 1.3
			#Range: 0.0 ~ 2.0E9
			FortuneCoefficient = 1.3
			#Range: 0.0 ~ 2.0E9
			SilktouchCoefficient = 2.0
			#Range: 0.0 ~ 2.0E9
			BaseMaxReceive = 100.0
			#Range: 0.0 ~ 2.0E9
			BasePower = 40.0
			#Range: 0.0 ~ 2.0E9
			BaseMaxStored = 1000.0

	#Setting of enabling or disabling each machine. True to disable.
	[common.machines]
		WorkbenchPlus = false
		QuarryPlus = true
		PumpPlus = false
		ModuleTorch = false
		ExpPump = false
		ModulePump = false
		EnchantMoverFromBook = true
		AdvancedPump = false
		MiningwellPlus = false
		Replacer = true
		SolidFuelQuarry = false
		ModuleFuel = false
		SpawnerController = true
		ChunkDestroyer = true
		NewQuarry = false
		EnchantMover = false
		ModuleReplacer = false
		ModuleExpPump = false
		MarkerPlus = false

